### ISSUE TITLE
sp_manifest is "empty" - CodeWalker

### ISSUE THREAD

**Issue by supergashbell** [TayMcKenzieNZ/server_scenarios#2]
So, unfortunately what I came across is this: 
- if I download your whole resource and I don't touch it, it works like stated and the animals actually spawn in the farm. 
- if I open sp_manifest.ymt with dev41, dev40 or dev39 of CodeWalker RPF Explorer, the document is blank and I can't export it to XML (Unable to convert file to XML)
- if I create a new sp_manifest with your raw code (that I can only see on Github) or modify my own from my game, the animals don't spawn in the farm.  

No errors or crashes, it simply doesn't work whenever I try to make an sp_manifest that is not the one that came with this repository. I really don't get it. Also, the size of my xml is equal to the ymt you have here, but If I convert it to ymt using codewalker, it becomes 20kb instead of 66kb.

**Comment by TayMcKenzieNZ** [comment]
I use notepad++ on Windows.

**Comment by TayMcKenzieNZ** [comment]
I also don't mess about with XML

**Comment by supergashbell** [comment]
Yeah, I've done the same with notepad++, it's the only way at the moment. I still haven't been able to delete (or move) scenario points on the beach ("country_club.ymt") because object spawns (such as sunloungers and parasols) are linked to different ymaps depending on the time (day/night/evening/morning) which define their position like normal entities but are spawned by the scenario (these ymap names are not specified inside CodeWalker Scenario editing). If anyone has to delete or move certain items spawned by a scenario, search for these ymaps using RPF Explorer (you can't see them in CW).

**Comment by TayMcKenzieNZ** [comment]
This is purely for modifying / adding scenarios, people who want to do mapping can do that themselves...
