### ISSUE TITLE
Crashing on the Airbase

### ISSUE THREAD

**Issue by CsyonDerEchte** [TayMcKenzieNZ/server_scenarios#4]
Hey when im using your script, im crashing all the time at the airbase (under Paleto). After removing it, everything works fine.

**Comment by TayMcKenzieNZ** [comment]
What airbase? Do you mean Fort Zancudo? If so, you can delete the scenario file for that area, edit sp_manifest.ymt and remove it from there as well, and then it should be good to go. 

I barely visit the north of the map but I'll check it out.

**Comment by CsyonDerEchte** [comment]
Yes Fort Zancudo. I'm on the forced game version mpsecurity. So maybe something changed in mpsecurity.

**Comment by TayMcKenzieNZ** [comment]
Possibly, but I doubt it. I might have messed something up with the fort zancudo scenario file. 

I always use the latest gamebuild, server artifacts etc etc and unfortunately although FiveM supports multiple gamebuilds, I can't be bothered to do so.

**Comment by CsyonDerEchte** [comment]
i replaced zancudo_river.ymt and lago_zancudo.ymt with the original gta files. This fixed it for me :)

**Comment by spider1987** [comment]
Hi 
any result ??

**Comment by TayMcKenzieNZ** [comment]
Literally read the message above you. I can't be bothered with maintaining this resource. It was released as a beta alpha or whatever. Figure it out and either delete or do it yourself.

**Comment by spider1987** [comment]
That was just a question sry
