### ISSUE TITLE
server_scenarios do not properly start with server startup

### ISSUE THREAD

**Issue by ZumieFiasco** [TayMcKenzieNZ/server_scenarios#5]
Hello, 

Reporting an issue since no other form support seems to be an option.
Platform: Fivem
Framework: QBCore

This script seemingly only works if I ensure it after server start up. It does not matter where it is in my server.cfg nor does it matter if its in a directory folder such as [standalone]. It simply does not work when server initiates and starts and someone with permissions has to go into the server and ensure the script or do it from txadmin console after server has started. This is the only time it works. 

I'm using mpsecurity build 2545

**Comment by TayMcKenzieNZ** [comment]
It is a standalone script and should not matter what crappy framework people are using. You need to add `ensure server_scenarios` in the server.cfg.

If it's not working as intended, then something soo small yet soo stupid, to do with qbcore, is interfering with it.

 As I do not use qbcore and it works fine for myself and everyone else, standalone, I cannot help you.

**Comment by TayMcKenzieNZ** [comment]
No conflict with other scripts of mine. If it works for your friend then, obviously it's something you're doing.

**Comment by ZumieFiasco** [comment]
Do you offer any support? I really like the resource and just want it start with server. I'm not "doing" anything. I'm trying to learn what could possibly interfere with it as it is standalone. Could you educate me on what file type or type(s) would interfere? I have a resource called "gabz_scenarios" maybe that could be interfering? I've also cross searched all files for .ymt files and such even tried looking in "server_scenarios" and searched for simliar file types (if any) and found none. 

I have the 'ensure server_scenarios' in my server.cfg, resource.cfg, and the resource itself is in my [standalone] folder. 

There is absolutely no reason it shouldn't work so I'm here as a last resort to ask you, the creator for guidance as I've done everything I can with my knowledge to get it to start with server and it won't.

**Comment by TayMcKenzieNZ** [comment]
I have no idea why you would need born server.cfg and resource.cfg, I suspect gabz_scenarios had similar files, therefore the server cancels itself out, and I don't work with frameworks so I have no idea. You said it works for your friend so this is unfortunately something you're going to have to figure out yourself. Disable and remove gabz_scenarios from your server and see if it works then, if it does then you know what the issue is, if it doesn't, keep looking through your server.

I can't offer support because I don't use frameworks and I don't know what's going on with your server, and I'm not going to gain access and look at it.

**Comment by TayMcKenzieNZ** [comment]
Clearly you have something conflicting with it and as I don't use QBCore or any framework, nor have access to their server, I can't pinpoint exactly what's wrong going on, however from experience with FiveM VPS servers, if the file exist more than once, it cancels itself out, like, if you have two MLOs with the same collision file, the 2nd MLO file gets ignored completely, or, they both load therefore cancelling out the collisions all together.

Delete your server cache, remove Gabz scenarios, check if everything is working. If not, look into my server_scenarios files and search your entire server for any duplicates.
